name: "CLA Assistant"

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    if: github.repository == 'hydro-dev/Hydro'
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: |
          github.event.comment.body == 'recheck' ||
          github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA' ||
          github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@ca4a40a7d1004f18d9960b404b97e5f30a505a08 # v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: ".github/cla-signatures.json"
          path-to-document: "https://github.com/hydro-dev/Hydro/blob/master/CLA.md"
          branch: "master"
          allowlist: undefined-moe,dependabot[bot]
          custom-pr-sign-comment: "I have read the CLA Document and I hereby sign the CLA"
          custom-notsigned-prcomment: "Thank you for your submission. We really appreciate it! Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/hydro-dev/Hydro/blob/master/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request comment same as the below format."
          lock-pullrequest-aftermerge: false
          signed-commit-message: "cla: @$contributorName has signed the CLA"